### ISSUE TITLE
Icon is not a moose

### ISSUE THREAD

**Issue by vitorgalvao** [ritz078/moose#95]
Is that on purpose? Your icon:
![](https://i.imgur.com/QPoRhth.png)

Silhouette of a moose:
![image](https://user-images.githubusercontent.com/1699443/86542839-47501000-bf11-11ea-970f-7db7580e955f.png)

**Comment by ritz078** [comment]
Thanks for this. You are right. The icon isn't a moose and it was intentional. This project was earlier named snape which had the deer logo but I didn't wanted to change that. I know this is a mismatch so I might change this in future. For now I am planning to keep it this way. Again thanks for pointing this out.
